// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates personalized cybersecurity recommendations based on assessment responses.
 *
 * - generateSecurityRecommendations - A function that generates security recommendations.
 * - GenerateSecurityRecommendationsInput - The input type for the generateSecurityRecommendations function.
 * - GenerateSecurityRecommendationsOutput - The return type for the generateSecurityRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSecurityRecommendationsInputSchema = z.object({
  assessmentResponses: z
    .record(z.string(), z.string())
    .describe('A record of assessment responses, where the key is the question ID and the value is the response.'),
});

export type GenerateSecurityRecommendationsInput = z.infer<
  typeof GenerateSecurityRecommendationsInputSchema
>;

const RecommendationSchema = z.object({
  recommendation: z.string().describe('A specific, actionable recommendation.'),
  priority: z
    .enum(['high', 'medium', 'low'])
    .describe('The priority of the recommendation.'),
});

const GenerateSecurityRecommendationsOutputSchema = z.object({
  risks: z.array(z.string()).describe('A list of the top identified risks.'),
  strengths: z
    .array(z.string())
    .describe('A list of the top identified strengths.'),
  recommendations: z
    .array(RecommendationSchema)
    .describe('A list of tailored recommendations.'),
});

export type GenerateSecurityRecommendationsOutput = z.infer<
  typeof GenerateSecurityRecommendationsOutputSchema
>;

export async function generateSecurityRecommendations(
  input: GenerateSecurityRecommendationsInput
): Promise<GenerateSecurityRecommendationsOutput> {
  return generateSecurityRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSecurityRecommendationsPrompt',
  input: {schema: GenerateSecurityRecommendationsInputSchema},
  output: {schema: GenerateSecurityRecommendationsOutputSchema},
  prompt: `You are an expert cybersecurity advisor for small and medium size enterprises (SMEs).
  Based on the SME's responses to a cybersecurity self-assessment, you will provide personalized and actionable recommendations.

  Your response should be simplified for smaller, non-enterprise companies.

  Assessment Responses:
  {{#each assessmentResponses}}
    {{@key}}: {{{this}}}
  {{/each}}

  Based on this user’s cybersecurity assessment, identify their top risks and strengths. Then, recommend tailored actions for the business to take. Prioritize recommendations into high, medium, and low priority action items.

  Return a JSON object with the following schema:
  ${JSON.stringify(GenerateSecurityRecommendationsOutputSchema.describe())}
  `,
});

const generateSecurityRecommendationsFlow = ai.defineFlow(
  {
    name: 'generateSecurityRecommendationsFlow',
    inputSchema: GenerateSecurityRecommendationsInputSchema,
    outputSchema: GenerateSecurityRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
