// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates personalized cybersecurity recommendations based on assessment responses.
 *
 * - generateSecurityRecommendations - A function that generates security recommendations.
 * - GenerateSecurityRecommendationsInput - The input type for the generateSecurityRecommendations function.
 * - GenerateSecurityRecommendationsOutput - The return type for the generateSecurityRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSecurityRecommendationsInputSchema = z.object({
  assessmentResponses: z
    .record(z.string(), z.string())
    .describe('A record of assessment responses, where the key is the question ID and the value is the response.'),
});

export type GenerateSecurityRecommendationsInput = z.infer<
  typeof GenerateSecurityRecommendationsInputSchema
>;

const RecommendationSchema = z.object({
  recommendation: z.string().describe('A specific, actionable recommendation.'),
  priority: z
    .enum(['high', 'medium', 'low'])
    .describe('The priority of the recommendation.'),
});

const GenerateSecurityRecommendationsOutputSchema = z.array(
  RecommendationSchema
);

export type GenerateSecurityRecommendationsOutput = z.infer<
  typeof GenerateSecurityRecommendationsOutputSchema
>;

export async function generateSecurityRecommendations(
  input: GenerateSecurityRecommendationsInput
): Promise<GenerateSecurityRecommendationsOutput> {
  return generateSecurityRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateSecurityRecommendationsPrompt',
  input: {schema: GenerateSecurityRecommendationsInputSchema},
  output: {schema: GenerateSecurityRecommendationsOutputSchema},
  prompt: `You are an expert cybersecurity advisor for small and medium size enterprises (SMEs).
  Based on the SME's responses to a cybersecurity self-assessment, you will provide personalized and actionable recommendations.

  Assessment Responses:
  {{#each assessmentResponses}}
    {{@key}}: {{{this}}}
  {{/each}}

  Prioritize recommendations into high, medium, and low priority action items.
  Return a JSON array of recommendations with the following schema:
  ${JSON.stringify(RecommendationSchema.describe())}
  `,
});

const generateSecurityRecommendationsFlow = ai.defineFlow(
  {
    name: 'generateSecurityRecommendationsFlow',
    inputSchema: GenerateSecurityRecommendationsInputSchema,
    outputSchema: GenerateSecurityRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
