'use client';
import {useEffect,useMemo,useState} from 'react';
import {ChevronLeft,ChevronRight,Loader2,RotateCcw} from 'lucide-react';
import Logo from '@/components/logo';
import {Button} from '@/components/ui/button';
import {Card,CardContent,CardDescription,CardFooter,CardHeader,CardTitle} from '@/components/ui/card';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Progress} from '@/components/ui/progress';
import {processAssessmentAction} from '@/lib/v2/actions';
import type {AnswerMap,Domain} from '@/lib/v2/schema';
import type {ClaritySnapshot} from '@/lib/v2/assessmentProcessor';
import {answerIsComplete,currentPath,parseV2Draft,progressFor,updateAnswer,V1_DRAFT_KEY,V2_DRAFT_KEY} from './v2Flow';

type Screen='landing'|'questions'|'processing'|'email'|'preview'|'results'|'error';
const domainLabels:Record<Domain,string>={business_context:'Business context',identity_access:'Identity & access',devices_updates:'Devices & updates',data_recovery:'Data & recovery',people_awareness:'People & awareness',visibility_response:'Visibility & response',responsibility:'Responsibility',ai_usage:'AI usage'};
const priorityLabels={address_first:'Worth addressing first',understand:'Worth understanding',positive:'A genuine strength'} as const;

export function ClarityV2App(){
 const[screen,setScreen]=useState<Screen>('landing');const[answers,setAnswers]=useState<AnswerMap>({});const[index,setIndex]=useState(0);const[snapshot,setSnapshot]=useState<ClaritySnapshot|null>(null);const[email,setEmail]=useState('');const[newsletter,setNewsletter]=useState(false);const[error,setError]=useState('');
 const path=useMemo(()=>currentPath(answers),[answers]);const question=path[Math.min(index,Math.max(0,path.length-1))];
 useEffect(()=>{try{sessionStorage.removeItem(V1_DRAFT_KEY);setAnswers(parseV2Draft(sessionStorage.getItem(V2_DRAFT_KEY)));}catch{}},[]);
 useEffect(()=>{try{if(Object.keys(answers).length)sessionStorage.setItem(V2_DRAFT_KEY,JSON.stringify(answers));}catch{}},[answers]);
 useEffect(()=>{if(index>=path.length)setIndex(Math.max(0,path.length-1));},[index,path.length]);
 const restart=()=>{setScreen('landing');setAnswers({});setIndex(0);setSnapshot(null);setEmail('');setNewsletter(false);setError('');try{sessionStorage.removeItem(V2_DRAFT_KEY);}catch{}};
 const finish=async()=>{setScreen('processing');setError('');const result=await processAssessmentAction(answers);if(result.snapshot){setSnapshot(result.snapshot);try{sessionStorage.removeItem(V2_DRAFT_KEY);}catch{}setScreen('email');}else{setError(result.error||'Unable to process assessment.');setScreen('error');}};
 const next=()=>{if(!question||!answerIsComplete(question,answers))return;if(index<path.length-1)setIndex(index+1);else void finish();};
 const showReport=()=>{if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){setError('Please enter a valid email address or leave the field blank.');return;}setError('');setScreen(email?'results':'preview');};
 const shell=(content:React.ReactNode)=><div role="main" className="flex min-h-svh w-full flex-col items-center justify-center p-4 md:p-8 bg-dot-pattern bg-subtle-animation bg-particles">{content}</div>;
 if(screen==='landing')return shell(<Card className="w-full max-w-2xl text-center border-border/50 bg-card/90"><CardHeader><div className="mx-auto mb-4"><Logo/></div><CardTitle className="text-4xl font-headline">Clarity by Tanosec</CardTitle><CardDescription className="text-lg">A contextual cybersecurity self-assessment for South African SMEs.</CardDescription></CardHeader><CardContent><Button size="lg" onClick={()=>setScreen('questions')}>Start assessment</Button></CardContent><CardFooter className="justify-center text-xs text-muted-foreground">Straightforward questions. No technical knowledge required.</CardFooter></Card>);
 if(screen==='processing')return shell(<div className="text-center space-y-5"><Loader2 className="mx-auto h-12 w-12 animate-spin text-primary"/><h1 className="text-2xl font-headline">Building your Clarity Snapshot…</h1><p className="text-muted-foreground">Looking at how your answers work together.</p></div>);
 if(screen==='error')return shell(<Card className="w-full max-w-lg text-center"><CardHeader><CardTitle>We could not complete the assessment</CardTitle><CardDescription>{error}</CardDescription></CardHeader><CardContent><Button onClick={()=>setScreen('questions')}>Review answers</Button></CardContent></Card>);
 if(screen==='questions'&&question)return shell(<div className="w-full max-w-3xl space-y-5"><div className="flex justify-center"><Logo size="small"/></div><div><div className="mb-2 flex justify-between text-sm"><span className="text-primary">{domainLabels[question.domain]}</span><span>Question {index+1} of {path.length}</span></div><Progress aria-label="Assessment progress" value={progressFor(index,path.length)} className="h-1"/></div><Card><CardHeader><CardTitle className="text-2xl">{question.wording}</CardTitle>{question.multiple&&<CardDescription>Select everything that applies.</CardDescription>}</CardHeader><CardContent className="space-y-3">{question.options.map(option=>{const selected=question.multiple?Array.isArray(answers[question.id])&&answers[question.id].includes(option.id):answers[question.id]===option.id;return question.multiple?<label key={option.id} className="flex cursor-pointer items-center gap-3 rounded-lg border p-4"><Checkbox checked={selected} onCheckedChange={checked=>setAnswers(updateAnswer(answers,question,option.id,checked===true))}/><span>{option.label}</span></label>:<Button key={option.id} type="button" variant={selected?'default':'outline'} className="h-auto w-full justify-start whitespace-normal p-4 text-left" onClick={()=>setAnswers(updateAnswer(answers,question,option.id))}>{option.label}</Button>;})}</CardContent><CardFooter className="justify-between"><Button variant="ghost" disabled={index===0} onClick={()=>setIndex(index-1)}><ChevronLeft className="mr-1 h-4 w-4"/>Back</Button><Button disabled={!answerIsComplete(question,answers)} onClick={next}>{index===path.length-1?'Finish':'Next'}<ChevronRight className="ml-1 h-4 w-4"/></Button></CardFooter></Card></div>);
 if(screen==='email'&&snapshot)return shell(<Card className="w-full max-w-xl text-center"><CardHeader><CardTitle>Your snapshot is ready</CardTitle><CardDescription>Email is optional. Continue without it to see a useful preview.</CardDescription></CardHeader><CardContent className="space-y-4 text-left"><div><Label htmlFor="v2-email">Email (optional)</Label><Input id="v2-email" type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="name@example.com"/></div><label className="flex items-center gap-2 text-sm"><Checkbox checked={newsletter} onCheckedChange={value=>setNewsletter(value===true)}/>Keep me updated on South African cyber threats</label><p className="text-xs text-muted-foreground">By providing your email you consent to Tanosec contacting you about this assessment in accordance with its Privacy Policy. POPIA compliant. No spam.</p>{error&&<p className="text-sm text-destructive">{error}</p>}</CardContent><CardFooter className="flex-col gap-2"><Button className="w-full" onClick={showReport}>{email?'Show my full snapshot':'Continue without email'}</Button></CardFooter></Card>);
 if((screen==='preview'||screen==='results')&&snapshot){const visible=screen==='preview'?snapshot.findings.slice(0,1):snapshot.findings;return shell(<div className="w-full max-w-4xl space-y-6"><div className="flex items-center justify-between gap-4"><div><Logo size="small"/><h1 className="mt-3 text-3xl font-headline">Your Clarity Snapshot</h1><p className="mt-2 text-muted-foreground">{snapshot.businessContext.summary}</p></div><Button variant="outline" onClick={restart}><RotateCcw className="mr-2 h-4 w-4"/>Start over</Button></div><div className="grid gap-4">{visible.map(finding=><Card key={finding.id}><CardHeader><CardDescription>{priorityLabels[finding.priority]}</CardDescription><CardTitle>{finding.title}</CardTitle></CardHeader><CardContent><p>{finding.explanation}</p></CardContent></Card>)}</div>{screen==='preview'?<Card><CardHeader><CardTitle>Want the full picture?</CardTitle><CardDescription>The remaining findings, evidence, and next actions will be available after the final results experience is completed.</CardDescription></CardHeader><CardContent><Button onClick={()=>setScreen('email')}>Add email for full snapshot</Button></CardContent></Card>:<><Card><CardHeader><CardTitle>Your next moves</CardTitle></CardHeader><CardContent className="space-y-3">{snapshot.nextActions.map(action=><div key={action.id} className="rounded-lg border p-4"><h2 className="font-semibold">{action.title}</h2><p className="text-sm text-muted-foreground">{action.description}</p></div>)}</CardContent></Card><p className="text-muted-foreground">{snapshot.closingNote}</p></>}</div>);}
 return shell(null);
}
