export type ExplanationFailureCategory='timeout'|'rate_limit'|'authentication'|'provider_unavailable'|'validation'|'unknown'|'circuit_open';
export interface ExplanationDiagnostics { source:'gemini'|'deterministic_fallback';attempts:number;latencyMs:number;failureCategory?:ExplanationFailureCategory }
export interface ReliabilityOptions { timeoutMs?:number;maxAttempts?:number;baseDelayMs?:number;now?:()=>number;sleep?:(ms:number)=>Promise<void> }
export interface CircuitBreaker { canAttempt():boolean;recordSuccess():void;recordFailure():void;state():{failures:number;openUntil:number} }
export function createCircuitBreaker(threshold=3,cooldownMs=60_000,now:()=>number=Date.now):CircuitBreaker{let failures=0,openUntil=0;return{canAttempt(){return now()>=openUntil;},recordSuccess(){failures=0;openUntil=0;},recordFailure(){failures+=1;if(failures>=threshold)openUntil=now()+cooldownMs;},state(){return{failures,openUntil};}};}
export function classifyExplanationFailure(error:unknown):ExplanationFailureCategory{const message=error instanceof Error?error.message.toLowerCase():String(error).toLowerCase();if(message.includes('timeout'))return'timeout';if(message.includes('429')||message.includes('quota')||message.includes('rate limit'))return'rate_limit';if(message.includes('401')||message.includes('403')||message.includes('api key')||message.includes('authentication'))return'authentication';if(message.includes('503')||message.includes('unavailable')||message.includes('high demand'))return'provider_unavailable';if(message.includes('explanation')||message.includes('json')||message.includes('finding'))return'validation';return'unknown';}
const transient=(category:ExplanationFailureCategory)=>['timeout','rate_limit','provider_unavailable'].includes(category);
async function withTimeout<T>(operation:()=>Promise<T>,timeoutMs:number):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([operation(),new Promise<T>((_,reject)=>{timer=setTimeout(()=>reject(new Error(`Explanation timeout after ${timeoutMs}ms`)),timeoutMs);})]);}finally{if(timer)clearTimeout(timer);}}
export async function executeReliableExplanation<T>(operation:()=>Promise<T>,breaker:CircuitBreaker,options:ReliabilityOptions={}):Promise<{value?:T;diagnostics:ExplanationDiagnostics}>{const timeoutMs=options.timeoutMs??5_500,maxAttempts=options.maxAttempts??1,baseDelayMs=options.baseDelayMs??250,now=options.now??Date.now,sleep=options.sleep??(ms=>new Promise(resolve=>setTimeout(resolve,ms)));const started=now();if(!breaker.canAttempt())return{diagnostics:{source:'deterministic_fallback',attempts:0,latencyMs:0,failureCategory:'circuit_open'}};let category:ExplanationFailureCategory='unknown';for(let attempt=1;attempt<=maxAttempts;attempt++){try{const value=await withTimeout(operation,timeoutMs);breaker.recordSuccess();return{value,diagnostics:{source:'gemini',attempts:attempt,latencyMs:Math.max(0,now()-started)}};}catch(error){category=classifyExplanationFailure(error);if(attempt<maxAttempts&&transient(category)){await sleep(baseDelayMs*attempt+Math.floor(Math.random()*50));continue;}breaker.recordFailure();return{diagnostics:{source:'deterministic_fallback',attempts:attempt,latencyMs:Math.max(0,now()-started),failureCategory:category}};}}return{diagnostics:{source:'deterministic_fallback',attempts:maxAttempts,latencyMs:Math.max(0,now()-started),failureCategory:category}};}
export const explanationCircuitBreaker=createCircuitBreaker();
