import type { NormalisedSignals } from './signals';
export type ContextLevel = 'strong'|'mixed'|'weak'|'unknown';
export interface DerivedContext { identity_dependency: 'high'|'moderate'|'low'; identity_protection: ContextLevel; recovery_confidence: ContextLevel; external_exposure_awareness: ContextLevel; security_awareness_effectiveness: ContextLevel; device_security_posture: ContextLevel; ai_data_exposure_risk: 'high'|'moderate'|'low'|'unknown'|'not_applicable'; breach_impact_potential: 'high'|'moderate'|'low'|'unknown'; governance_clarity: ContextLevel }
const includesAny = (values: readonly string[], wanted: string[]) => wanted.some(value => values.includes(value));
export function deriveContext(s: NormalisedSignals): DerivedContext {
  const identityDependency = includesAny(s.criticalSystems, ['email','cloud_files','accounting','customer_data','line_of_business']) ? 'high' : s.workModel === 'remote' || s.workModel === 'hybrid' ? 'moderate' : 'low';
  const identityProtection = [s.mfa,s.offboarding,s.accountSharing].includes('unknown') ? 'unknown' : s.mfa === 'full' && s.offboarding === 'same_day' && s.accountSharing === 'individual' ? 'strong' : s.mfa === 'none' || s.offboarding === 'ad_hoc' || s.accountSharing === 'many_shared' ? 'weak' : 'mixed';
  const recovery = s.backups === 'unknown' ? 'unknown' : s.backups === 'none' ? 'weak' : s.backups === 'full' && ['three_months','year'].includes(s.restoreTest) ? 'strong' : 'mixed';
  const awareness = [s.training,s.reporting].includes('unknown') ? 'unknown' : s.training === 'yes' && s.reporting === 'clear' ? 'strong' : s.training === 'no' || s.reporting === 'none' ? 'weak' : 'mixed';
  const devices = [s.endpointProtection,s.patching].includes('unknown') ? 'unknown' : s.endpointProtection === 'yes' && s.patching === 'automatic' ? 'strong' : s.endpointProtection === 'no' || s.patching === 'delayed' ? 'weak' : 'mixed';
  const aiRisk = ['none','unaware'].includes(s.aiUsage) ? 'not_applicable' : s.aiUsage === 'unknown' || s.aiDataRules === 'unknown' ? 'unknown' : ['high','medium'].includes(s.dataSensitivity) && s.aiDataRules === 'none' ? 'high' : s.aiDataRules === 'informal' || ['sometimes','rarely'].includes(s.aiHumanReview) ? 'moderate' : 'low';
  return { identity_dependency: identityDependency, identity_protection: identityProtection, recovery_confidence: recovery, external_exposure_awareness: s.externalExposure === 'known' ? 'strong' : s.externalExposure === 'mostly' ? 'mixed' : s.externalExposure === 'not_known' ? 'weak' : 'unknown', security_awareness_effectiveness: awareness, device_security_posture: devices, ai_data_exposure_risk: aiRisk, breach_impact_potential: s.dataSensitivity === 'unknown' ? 'unknown' : s.dataSensitivity === 'high' || s.criticalSystems.length >= 3 ? 'high' : s.dataSensitivity === 'medium' || s.criticalSystems.length ? 'moderate' : 'low', governance_clarity: s.securityOwner === 'clear' ? 'strong' : s.securityOwner === 'shared' ? 'mixed' : s.securityOwner === 'none' ? 'weak' : 'unknown' };
}
