import type { RawFinding } from './rules';
export const TANOSEC_SERVICE_IDS = ['digital_footprint','vulnerability_assessment','penetration_testing','security_awareness','phishing_simulation','managed_security','cybersecurity_consulting','data_privacy'] as const;
export type TanosecServiceId = typeof TANOSEC_SERVICE_IDS[number];
export type AssistanceType = 'self_help'|'tanosec_service'|'specialist';
export interface ActionTemplate { id: string; title: string; description: string; type: AssistanceType; serviceId?: TanosecServiceId }
const action = (id:string,title:string,description:string,type:AssistanceType='self_help',serviceId?:TanosecServiceId):ActionTemplate => ({id,title,description,type,serviceId});
export const ACTIONS: Readonly<Record<string,ActionTemplate>> = Object.fromEntries([
  action('enable_mfa','Extend MFA to important accounts','Start with email, cloud files, finance, and administrator accounts.'), action('remove_shared_accounts','Replace shared accounts','Give each person an account and review permissions.'), action('establish_backups','Establish a recoverable backup','Back up important data separately and document how to restore it.'), action('test_restore','Run a real restore test','Restore a representative file or system and record the result.'), action('map_exposure','Map internet-facing systems','List domains, services, remote access, and responsible owners.','tanosec_service','digital_footprint'), action('define_reporting','Define a reporting route','Give everyone one clear way to report suspicious activity.'), action('awareness_basics','Give the team practical guidance','Cover phishing, passwords, reporting, and sensitive information.','tanosec_service','security_awareness'), action('automate_updates','Automate security updates','Enable automatic updates and review devices that cannot comply.'), action('endpoint_baseline','Set a device protection baseline','Confirm endpoint protection is active on every business device.'), action('check_devices','Check device controls','Inventory devices and verify protection, updates, and remote-lock capability.'), action('write_response_steps','Write first-response steps','Document who to contact, how to contain access, and what evidence to preserve.','specialist'), action('review_alerts','Review important alerts','Enable sign-in alerts and name someone to review them.'), action('assign_owner','Assign a security owner','Name one accountable person even if delivery is shared.'), action('define_ai_rules','Set practical AI data rules','State what may never be entered and when human review is required.','tanosec_service','data_privacy'), action('check_ai_use','Ask how AI is being used','Run a short, non-punitive check before setting rules.'), action('maintain_identity','Keep identity controls reviewed','Review MFA, leavers, and shared accounts periodically.'), action('maintain_recovery','Keep testing recovery','Repeat restore tests after meaningful changes.'), action('maintain_awareness','Keep awareness practical','Refresh guidance and reporting exercises periodically.'),
].map(item => [item.id,item]));
export function selectFindings(candidates: readonly RawFinding[], maximum=3): RawFinding[] { const ordered=[...candidates].sort((a,b)=>b.rank-a.rank||a.id.localeCompare(b.id)); const selected:RawFinding[]=[]; for(const item of ordered){ if(selected.some(existing=>existing.category===item.category)) continue; selected.push(item); if(selected.length===maximum) break; } if(selected.length<maximum) for(const item of ordered) if(!selected.includes(item)){ selected.push(item); if(selected.length===maximum) break; } return selected; }
export function resolveActions(allCandidates: readonly RawFinding[], maximum=3): ActionTemplate[] { const seen=new Set<string>(); const resolved:ActionTemplate[]=[]; for(const finding of [...allCandidates].sort((a,b)=>b.rank-a.rank||a.id.localeCompare(b.id))) for(const id of finding.actionIds){ if(seen.has(id)||!ACTIONS[id]) continue; seen.add(id); resolved.push(ACTIONS[id]); if(resolved.length===maximum) return resolved; } return resolved; }
