import { describe, expect, it } from 'vitest';
import { buildInternalEmailHtml, buildPdfSections, buildUserEmailHtml, buildWhatsAppText, toPublicSnapshot } from './reporting';

const snapshot = toPublicSnapshot({ version:'2.0', businessContext:{companySize:'6_20',sector:'legal',workModel:'hybrid',summary:'A small hybrid legal practice'}, findings:[{id:'f1',priority:'address_first',title:'Account access deserves attention',explanation:'Extend protection to important accounts.'},{id:'f2',priority:'positive',title:'Recovery is tested',explanation:'Restore testing is a genuine strength.'}], evidencePanels:[{findingId:'f1',statements:['MFA is only partly enabled.']}], nextActions:[{id:'a1',title:'Extend MFA',description:'Start with email and finance.',type:'self_help'}], closingNote:'Take one practical step at a time.', explanationDiagnostics:{source:'gemini',attempts:1,latencyMs:4}, generatedAt:'2026-08-26T12:00:00.000Z' });

describe('Phase 6 reporting',()=>{
  it('renders every finding and evidence in the standalone email',()=>{const html=buildUserEmailHtml(snapshot);expect(html).toContain('Account access deserves attention');expect(html).toContain('Recovery is tested');expect(html).toContain('MFA is only partly enabled.');});
  it('omits prohibited and internal metadata from user output',()=>expect(buildUserEmailHtml(snapshot)).not.toMatch(/percentage|risk band|benchmark|explanationDiagnostics|latencyMs|rule ID/i));
  it('omits strengths and actions sections when absent',()=>{const empty={...snapshot,findings:snapshot.findings.filter(f=>f.priority!=='positive'),nextActions:[]};const html=buildUserEmailHtml(empty);expect(html).not.toContain('What you’re doing well');expect(html).not.toContain('Your next moves');});
  it('builds PDF content for findings, evidence, actions and positive-only results',()=>{const text=buildPdfSections(snapshot).flatMap(section=>[section.heading,...section.items]).join(' ');expect(text).toContain('Account access deserves attention');expect(text).toContain('MFA is only partly enabled.');expect(text).toContain('Extend MFA');const positive={...snapshot,findings:snapshot.findings.filter(f=>f.priority==='positive')};expect(buildPdfSections(positive).some(section=>section.heading==='What you’re doing well')).toBe(true);});
  it('omits the positive PDF section when there is no positive finding',()=>expect(buildPdfSections({...snapshot,findings:snapshot.findings.filter(f=>f.priority!=='positive')}).some(section=>section.heading==='What you’re doing well')).toBe(false));
  it('uses finding titles in concise internal notifications without newsletter metadata',()=>{const email=buildInternalEmailHtml(snapshot,'owner@example.com');const whatsapp=buildWhatsAppText(snapshot,'owner@example.com');expect(email).toContain('Account access deserves attention');expect(whatsapp).toContain('Main finding: Account access deserves attention');expect(`${email}${whatsapp}`).not.toMatch(/percentage|risk band|benchmark|newsletter|explanationDiagnostics|raw signal/i);});
  it('strips internal diagnostics at the trust boundary',()=>expect(toPublicSnapshot(snapshot)).not.toHaveProperty('explanationDiagnostics'));
  it('escapes injected markup and rejects invented report metadata',()=>{const hostile=toPublicSnapshot({...snapshot,findings:[{...snapshot.findings[0],title:'<img src=x onerror=alert(1)>'}]});expect(buildUserEmailHtml(hostile)).toContain('&lt;img');expect(()=>toPublicSnapshot({...snapshot,findings:[{...snapshot.findings[0],priority:'critical'}]})).toThrow('Invalid finding');expect(()=>toPublicSnapshot({...snapshot,nextActions:[{id:'x',title:'x',description:'x',type:'incident_response'}]})).toThrow('Invalid action');});
});
