import type { DerivedContext } from './context';
import type { NormalisedSignals } from './signals';
export type FindingPriority = 'address_first'|'understand'|'positive';
export interface RuleInput { signals: NormalisedSignals; context: DerivedContext }
export interface Evidence { signal: keyof NormalisedSignals; value: string; statement: string }
export interface RawFinding { id: string; category: string; priority: FindingPriority; rank: number; title: string; rationale: string; evidence: Evidence[]; actionIds: string[] }
export interface ContextualRule { id: string; evaluate(input: RuleInput): RawFinding|null }
const finding = (id: string, category: string, priority: FindingPriority, rank: number, title: string, rationale: string, actionIds: string[], evidence: Evidence[]): RawFinding => ({ id, category, priority, rank, title, rationale, actionIds, evidence });
const ev = <K extends keyof NormalisedSignals>(signal: K, value: NormalisedSignals[K], statement: string): Evidence => ({ signal, value: Array.isArray(value) ? value.join(',') : String(value), statement });
export const RULES: readonly ContextualRule[] = [
  { id:'identity_compound', evaluate:({signals:s,context:c}) => c.identity_dependency === 'high' && c.identity_protection === 'weak' ? finding('identity_compound','identity','address_first',100,'Account access deserves attention first','Important systems depend on identities that are not consistently protected.',['enable_mfa','remove_shared_accounts'],[ev('mfa',s.mfa,'MFA coverage is weak'),ev('accountSharing',s.accountSharing,'Accounts may be shared')]) : null },
  { id:'recovery_absent', evaluate:({signals:s,context:c}) => s.backups === 'none' && c.breach_impact_potential !== 'low' ? finding('recovery_absent','recovery','address_first',98,'There is no dependable recovery path','Important work may not be recoverable after disruption.',['establish_backups'],[ev('backups',s.backups,'Important files are not backed up')]) : null },
  { id:'recovery_untested', evaluate:({signals:s}) => ['full','partial'].includes(s.backups) && ['old','never'].includes(s.restoreTest) ? finding('recovery_untested','recovery','address_first',88,'Backups exist, but recovery is uncertain','A restore test is the only reliable proof that backups can be used.',['test_restore'],[ev('backups',s.backups,'Backups exist'),ev('restoreTest',s.restoreTest,'Recovery has not been tested recently')]) : null },
  { id:'external_unknown', evaluate:({signals:s,context:c}) => ['weak','unknown'].includes(c.external_exposure_awareness) ? finding('external_unknown','visibility','understand',75,'Your external exposure may not be fully visible','Mapping public systems creates a reliable starting point.',['map_exposure'],[ev('externalExposure',s.externalExposure,'Internet-facing systems are not fully known')]) : null },
  { id:'awareness_reporting_gap', evaluate:({signals:s}) => ['yes','partial'].includes(s.training) && ['none','unknown'].includes(s.reporting) ? finding('awareness_reporting_gap','people','understand',70,'People may spot a threat but not know what to do next','Training is more effective when reporting is clear.',['define_reporting'],[ev('training',s.training,'Some awareness training exists'),ev('reporting',s.reporting,'Reporting is unclear')]) : null },
  { id:'awareness_weak', evaluate:({signals:s,context:c}) => c.security_awareness_effectiveness === 'weak' ? finding('awareness_weak','people','understand',66,'Practical security habits could be strengthened','Training and a clear reporting route reduce avoidable uncertainty.',['awareness_basics'],[ev('training',s.training,'Training coverage is weak'),ev('reporting',s.reporting,'Reporting may be unclear')]) : null },
  { id:'device_weak', evaluate:({signals:s,context:c}) => c.device_security_posture === 'weak' ? finding('device_weak','devices','address_first',82,'Device protections are inconsistent','Delayed updates or missing endpoint protection leave preventable gaps.',['automate_updates','endpoint_baseline'],[ev('endpointProtection',s.endpointProtection,'Endpoint protection is weak'),ev('patching',s.patching,'Updates may be delayed')]) : null },
  { id:'device_unknown', evaluate:({signals:s,context:c}) => c.device_security_posture === 'unknown' ? finding('device_unknown','devices','understand',48,'Device protection is worth checking','Some device controls are not currently known.',['check_devices'],[ev('endpointProtection',s.endpointProtection,'Device protection is uncertain')]) : null },
  { id:'incident_gap', evaluate:({signals:s}) => s.incidentReadiness === 'none' ? finding('incident_gap','response','address_first',78,'A compromised account could create avoidable confusion','A short first-response checklist helps people act quickly and calmly.',['write_response_steps'],[ev('incidentReadiness',s.incidentReadiness,'No first-response process is known')]) : null },
  { id:'monitoring_gap', evaluate:({signals:s}) => ['none','unreviewed'].includes(s.monitoring) ? finding('monitoring_gap','visibility','understand',64,'Suspicious activity may go unnoticed','Alerts only help when they exist and someone reviews them.',['review_alerts'],[ev('monitoring',s.monitoring,'Login alerts are absent or unreviewed')]) : null },
  { id:'governance_gap', evaluate:({signals:s,context:c}) => c.governance_clarity === 'weak' ? finding('governance_gap','governance','understand',52,'Security decisions do not have a clear owner','Clear responsibility makes follow-through more reliable.',['assign_owner'],[ev('securityOwner',s.securityOwner,'No clear security owner exists')]) : null },
  { id:'ai_confirmed_risk', evaluate:({signals:s,context:c}) => c.ai_data_exposure_risk === 'high' ? finding('ai_confirmed_risk','ai','address_first',84,'AI use may be creating a data-handling blind spot','Confirmed AI use and sensitive information need clear handling boundaries.',['define_ai_rules'],[ev('aiUsage',s.aiUsage,'AI is used for work'),ev('aiDataRules',s.aiDataRules,'No clear data rules exist')]) : null },
  { id:'ai_visibility', evaluate:({signals:s}) => ['unaware','unknown'].includes(s.aiUsage) ? finding('ai_visibility','ai','understand',42,'You may not have a clear picture of workplace AI use','Uncertainty is a visibility question, not proof of unsafe use.',['check_ai_use'],[ev('aiUsage',s.aiUsage,'AI use is not currently known')]) : null },
  { id:'identity_strong', evaluate:({signals:s,context:c}) => c.identity_protection === 'strong' ? finding('identity_strong','identity','positive',30,'Important accounts have strong foundations','MFA, individual accounts, and prompt offboarding work together.',['maintain_identity'],[ev('mfa',s.mfa,'MFA coverage is strong')]) : null },
  { id:'recovery_strong', evaluate:({signals:s,context:c}) => c.recovery_confidence === 'strong' ? finding('recovery_strong','recovery','positive',28,'Recovery has been proven recently','Backups are present and restore testing provides real confidence.',['maintain_recovery'],[ev('restoreTest',s.restoreTest,'A recent restore test was completed')]) : null },
  { id:'awareness_strong', evaluate:({signals:s,context:c}) => c.security_awareness_effectiveness === 'strong' ? finding('awareness_strong','people','positive',26,'Your team has practical security support','Training, reporting, and testing reinforce one another.',['maintain_awareness'],[ev('training',s.training,'Training is current')]) : null },
];
export const runRules = (input: RuleInput): RawFinding[] => RULES.map(rule => rule.evaluate(input)).filter((value): value is RawFinding => value !== null);
